allowBuilds:
  '@clerk/shared': false
  '@prisma/client': false
  '@prisma/engines': false
  prisma: false
  sharp: false
  unrs-resolver: false
overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.5
